version: '3.7'
services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db/data:/var/lib/mysql
      # dumpファイル等の格納
      - ./db/temp:/var/tmp/temp
    command: mysqld --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
